export const ActionTypes = {
    ADD_AMOUNT: "ADD_AMOUNT",
    HIGHLIGHT: "HIGHLIGHT",
    UNHIGHLIGHT: "UNHIGHLIGHT",
    SET_CONSTS: "SET_CONSTS",
    ADD_ROW: "ADD_ROW",
    REMOVE_ROW: "REMOVE_ROW",
    HIGHLIGHT_SUM: "HIGHLIGHT_SUM",
    UNHIGHLIGHT_SUM: "UNHIGHLIGHT_SUM",
} as const;
